-- 코드를 작성해주세요
SELECT a.ITEM_ID, a.ITEM_NAME, a.RARITY
FROM ITEM_INFO a
LEFT JOIN (SELECT PARENT_ITEM_ID FROM ITEM_TREE GROUP BY PARENT_ITEM_ID) b
ON a.ITEM_ID = b.PARENT_ITEM_ID
WHERE b.PARENT_ITEM_ID is null
ORDER BY a.ITEM_ID desc;