-- 코드를 작성해주세요
SELECT a.ID, IFNULL(b.CHILD_COUNT,0) as CHILD_COUNT
FROM ECOLI_DATA a
left join (SELECT PARENT_ID, COUNT(*) as CHILD_COUNT FROM ECOLI_DATA GROUP BY PARENT_ID) b
ON a.ID = b.PARENT_ID
ORDER BY a.ID asc;