SELECT
    u.USER_ID,
    u.NICKNAME,
    CONCAT(u.CITY, " ", u.STREET_ADDRESS1, " ", u.STREET_ADDRESS2) as 전체주소,
    CONCAT(SUBSTR(TLNO,1,3),"-",SUBSTR(TLNO,4,4),"-",SUBSTR(TLNO,8,4)) as 전화번호
FROM 
    USED_GOODS_USER u,
    (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(WRITER_ID) >= 3) b
WHERE
    u.USER_ID = b.WRITER_ID
ORDER BY
    USER_ID desc;
